[[redirects]]
  from = "https://link-in-bio.netlify.com/*"
  to = "https://link-in-bio.herokuapp.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200